raider_hacks/posts/routes.py
from flask import Blueprint, render_template, Markup
import markdown
import markdown.extensions.fenced_code
from pygments.formatters import HtmlFormatter
import logging
from flask import request, redirect, url_for, flash
from flask import Blueprint, render_template
from passlib.hash import sha256_crypt
from sqlalchemy import or_
from flask_login import login_user, logout_user, login_required, current_user

from raider_hacks.forms import PostForm

from raider_hacks import app, db, mail, Message
from raider_hacks.models import User, Post


post_bp = Blueprint('post', __name__,
    template_folder='templates',
    static_folder='static'
)


@post_bp.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():

    result = User.query.filter_by(email=current_user.email).first()

    # if the admin feild is not true retun 404
    if result.permissions != 3:
        return "<h1> You do not have permissions to view this page</h1>" 
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user, permissions=form.permissions.data)
        # convert to markdown before sending
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('index'))
    return render_template('posts/create_post.html', title='New Post', form=form, legend='New Post', whoami=result)

@post_bp.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)

    # convert to markdown
    md_template = markdown.markdown(post.content, extensions=["fenced_code", "codehilite"])

    # format code blocks with css  
    formatter = HtmlFormatter(style="tango",full=True,cssclass="codehilite")
    css_string = formatter.get_style_defs()
    md_css_string = "<style>" + css_string + "</style>"
    # conacatinate css and html markdown
    html_md = md_css_string + md_template 

    return render_template('posts/post.html', title=post.title, post=post, html_md=Markup(html_md))

@post_bp.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('posts/create_post.html', title='Update Post', form=form, legend='Update Post')

@post_bp.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('index'))

raider_hacks/posts/templates/posts/create_post.html
{% extends "layout.html" %}
{% block content %}
<link rel="stylesheet" href="raider_hacks/static/styles/create_post.css">
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group" id="content">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        
        <div class="form-group"> 
            {{ form.permissions.label }}
            <br>
            {% for option in form.permissions %}
                {{ option.label }} 
                {{ option }} 
                <br>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
      <h1> {{ whoami }}</h1>
</div>
{% endblock content %}

raider_hacks/posts/templates/posts/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('post.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            <p> Post Permissions level: {{ post.permissions }} </p>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>

        {{ html_md }}


    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('post.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
    
  </div>
{% endblock content %}