raider_hacks/members/routes.py
import os, secrets
from PIL import Image
from flask import Blueprint, render_template, url_for, flash, request, redirect 
from flask_login import login_user, logout_user, login_required, current_user

# import member form
from raider_hacks.forms import NewMember
# import db modles 
from raider_hacks.models import Member, User
# import actual db
from raider_hacks import db, app


members_bp = Blueprint( 'members', __name__,
        template_folder='templates',
        static_folder='static'
)


@members_bp.route("/members") 
def members():
        members = Member.query.all()
        return render_template('members/members.html', members=members)

def save_image(form_image):
        random_hex = secrets.token_hex(8)
        _, f_ext = os.path.splitext(form_image.filename)
        image_fn = random_hex + f_ext
        image_path = os.path.join(app.root_path, 'static/images/profile_pics', image_fn)

        output_size = (300,300)
        i = Image.open(form_image)
        i.thumbnail(output_size)
        i.save(image_path)

        return image_fn

@members_bp.route("/member/<int:member_id>")
def member(member_id):

        member = Member.query.get_or_404(member_id)
        user = ''

        if current_user.is_anonymous == False:

                user = User.query.filter_by(email=current_user.email).first()
                return render_template('members/member.html', member=member, user=user)

        else:
                return render_template('members/member.html', member=member, user=user)



@members_bp.route("/member/new", methods=['GET', 'POST'])
@login_required
def make_member():

        result = User.query.filter_by(email=current_user.email).first()
        # if the admin feild is not true retun 404
        if result.permissions != 3:
                return "<h1> You do not have permissions to view this page</h1>" 

        form = NewMember()
        if request.method == 'POST' and form.validate_on_submit:

                image_file = save_image(form.profile_pic.data)

                # build member from form data
                member = Member(
                fname=form.fname.data, 
                lname=form.lname.data, 
                email=form.email.data, 
                bio=form.bio.data, 
                profile_pic=image_file)
                # add member to database 
                db.session.add(member)
                db.session.commit()
                flash('You added a member', 'success')
        elif request.method == 'GET':
                return render_template('members/new_member.html', form=form)

        return render_template('members/new_member.html', form=form)


@members_bp.route("/member/<int:member_id>/update", methods=['GET', 'POST'])
@login_required
def update_member(member_id):
        # check user permissions
        result = User.query.filter_by(email=current_user.email).first()
        # if the admin feild is not true retun 404
        if result.permissions != 3:
                return "<h1> You do not have permissions to view this page</h1>" 

        # queary the member data using the member id
        member = Member.query.get_or_404(member_id) 
        form = NewMember()
        if form.validate_on_submit and request.method == 'POST': 

                image_file = save_image(form.profile_pic.data)
                member.fname = form.fname.data
                member.lname = form.lname.data
                member.email = form.email.data
                member.bio = form.bio.data
                member.profile_pic = image_file 

                db.session.commit()
                flash('Your post has been updated!', 'success')
                return redirect(url_for('members.member', member_id=member.id))

        # populate the form data using the data we quiered from the member_id 
        elif request.method == 'GET':
                form.fname.data = member.fname
                form.lname.data = member.lname
                form.email.data = member.email 
                form.bio.data = member.bio 
                form.profile_pic.data = member.profile_pic 

        return render_template('members/new_member.html', form=form)

@members_bp.route("/member/<int:member_id>/delete", methods=['POST'])
@login_required
def delete_member(member_id):
        # check user permmisions
        result = User.query.filter_by(email=current_user.email).first()
        # if the admin feild is not true retun 404
        if result.permissions != 3:
                return "<h1> You do not have permissions to view this page</h1>" 

        member = Member.query.get_or_404(member_id)
        
        db.session.delete(member)
        db.session.commit()
        flash('Your post has been deleted!', 'success')
        return redirect(url_for('index'))

raider_hacks/members/templates/members/member.html
{% extends "layout.html"%}

{% block header %}
{% endblock%}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/member.css') }}"> 
            <div class="container pt-2 px-3 px-sm-0">
                <div class="d-lg-block">
                    <div class="d-flex flex-column-reverse flex-md-row">
                        <div class="w-md-60">
                            <div class="my-5 px-3 px-lg-0">
                                <h1 class="h3 space-mono mb-1"> {{ member.fname }} {{ member.lname }} </h1>
                    
                            </div>
                            <div class="mr-4 float-none float-md-left profile-photo">
                                <div class="mt-1 mb-3 px-3 px-lg-0 position-relative">
                                <img alt="{{ member.fname }}"
                                        class="position-relative"
                                        style="margin-left: 20px; object-fit: cover; z-index: 1;"
                                        src= "../static/images/profile_pics/{{ member.profile_pic }} "   
                                >
                                </div>
                                <div class="pt-4 pb-3 px-4">
                                   
                    
                                </div>
                            </div>
                            <div class="mt-4">
                              {{ member.bio }} 
                           
                        </div>
                      
                        </div>
                </div>
      
            </div>
        {% if user.permissions == 3 %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('members.update_member', member_id=member.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>

        {% endif %} 
   <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
         <form action="{{ url_for('members.delete_member', member_id=member.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  
   {{ member.profile_pic }}
   {{ member.fname }} 
   {{ member.lname }} 



{% endblock %}

raider_hacks/members/templates/members/members.html
{% extends "layout.html" %}

{% block header %}

{% endblock%}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/members.css') }}">
<main role="main">

    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Membership</h1>
        <p class="lead text-muted">
	RaiderHacks members come from a diverse background of academic disciplines, no programming knowledge is required to join and there are no dues. Fill out this <a href="#sign-up-form">form</a> and we will reach out with more information on how you can join. 
	</p>
      </div>
    </section>

    <div class="album py-5 bg-light">
      <div class="container">

        <div class="row">
          {% for member in members %}
          <div class="col-md-4">
            <a href="{{ url_for('members.member', member_id=member.id) }}">

            <div class="card mb-4 box-shadow">
              <div>
              <img class="card-img" src="static/images/profile_pics/{{ member.profile_pic }}" alt="Card image cap">
              <div class="card-img-overlay"> 
                <h5 class="card-title" id="cn"> {{ member.fname }} {{ member.lname }} </h5>

              </div>
            </div>
            
            </a>  
            
            </div>
          </div>

          {% endfor %}

      
      
        </div>
      </div>
    </div>
    
 <div  class="row" id="sign-up-form">

	<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScfA3JfDAE7yxncOYVsD_eeoNQ3TVJdRW9A3oJ1R1Yy8q9eDA/viewform?embedded=true" width="640" height="964" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

 </div>
  </main>




   
 

{% endblock %} 

raider_hacks/members/templates/members/members2.html
{% extends "layout.html" %}

{% block header %}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/members.css') }}">
    <div class="jumbotron jumbotron-fluid bg-info text-white text-center">
    <div class="container">
    <h1 class="display-3">Members</h1>
    </div>
    </div>

    <div class=".container-fluid">
    <div class="row justify-content-center">
    {% for member in members %}
        <div class=".col-12 .col-md-6 p-5 m-5">
            <h3 class="text-primary texty"> {{ member.fname }} {{ member.lname }} </h3>

            
             <div class="img">
              <img src="static/images/profile_pics/{{ member.profile_pic }}" class="img-fluid" alt="Responsive image">
            </div>


            <ul class="nav .text-center">
                <li class="nav-item mx-auto">
                <a class="nav-link .text-center" href="{{ url_for('members.member', member_id=member.id) }}"> read more about {{ member.fname }}</a></h2>

                </li>
            </ul>

        </div>
       

    {% endfor %}





{% endblock %} 

raider_hacks/members/templates/members/new_member.html
{% extends "layout.html" %}
{% block content %} 
<link rel="stylesheet" href="{{ url_for('static', filename='styles/new_member.css') }}"> 
    
    <div class="content-section">
        <h1 class="text-center"> Add Member </h1>
        <form method="POST" action="" enctype="multipart/form-data">
           <fieldset class="form-group">
                <div class="form-group">
                    <legend class="border-bottom mb-4">{{ legend }}</legend>
                    {{ form.fname.label(class="form-control-label") }}
                    <br>
                    {{ form.fname }}
                </div>

                <div class="form-group">
                    {{ form.lname.label(class="form-control-label") }}
                    <br>
                    {{ form.lname }}
                </div>

                <div class="form-group"> 
                    {{ form.email.label(class="form-control-label") }}
                    <br>
                    {{ form.email }}
                </div>

                <div class"form-group">
                    {{ form.bio.label(class="form-control-label") }}
                    <br>
                    {{ form.bio(id="bio") }} 
                </div>

                <div class="form-group" >
                    {{ form.profile_pic.label(class="form-control-label") }}
                    <br>
                    {{ form.profile_pic }}
                </div>

                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </fieldset>

    </div>
    <form>
{% endblock content %}